### ISSUE TITLE
[1.12.2-1.0.5] Unexpected error: NullPointerException

### ISSUE THREAD

**Issue by judgekreep** [Meldexun/ReachFix#2]
I got this error 2 days ago and forgot to report it.
I don't recall what I was doing but hopefully the crash report says enough. 

```
Description: Unexpected error

java.lang.NullPointerException
    at meldexun.reachfix.hook.client.EntityRendererHook.getMouseOver(EntityRendererHook.java:53)
    at net.minecraft.client.renderer.EntityRenderer.getMouseOver(EntityRenderer.java)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1597)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1390)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

Full crash report: https://pastebin.com/mCdWu7Nf

**Comment by Meldexun** [comment]
I don't know what could cause a NPE here. So unless you can somehow reproduce this I can't do anything here.

**Comment by Meldexun** [comment]
Is this reproducible or did this happen more than once?

**Comment by Foulest** [comment]
Bump: https://mclo.gs/igXvz8w

I was in a Pixelmon fight. Similar mods list.

**Comment by Foulest** [comment]
Fixed in #9

**Comment by Meldexun** [comment]
> Bump: https://mclo.gs/igXvz8w
> 
> I was in a Pixelmon fight. Similar mods list.

Same question, is this reproducible or did this happen more than once?

**Comment by Foulest** [comment]
This is reproducible: throw your currently selected Pokemon at a wild Pokemon from a far away distance. Once in battle, use an attacking move.

**Comment by Foulest** [comment]
I believe I've fixed it. After diagnosing this for over an hour, the issue lies within referencing mc.objectMouseOver.entityHit. I've attached some code below. Consider this an amendment for my horrible pull request earlier.

```
public static void getMouseOver(float partialTicks) {
        @NotNull Minecraft mc = Minecraft.getMinecraft();
        @Nullable Entity viewEntity = mc.getRenderViewEntity();
        EntityPlayerSP player = mc.player;
        WorldClient world = mc.world;

        // Checks for exceptions.
        if (viewEntity == null || player == null || world == null) {
            return;
        }

        // Starts the pick section.
        mc.profiler.startSection("pick");

        @NotNull RayTraceResult result = pointedObject(viewEntity, player, EnumHand.MAIN_HAND, world, partialTicks);

        // This is EXTREMELY IMPORTANT! Storing the entityHit here and referencing
        // it instead of the mc.objectMouseOver.entityHit field is what allows us to
        // not have NPEs randomly thrown! For some reason, referencing the field
        // in mc.objectMouseOver.entityHit causes NPEs to be thrown randomly.
        // mc.objectMouseOver.entityHit is the same as result.entityHit.
        Entity entityHit = result.entityHit;

        // Assigns the result to the objectMouseOver field in the Minecraft class.
        mc.objectMouseOver = result;

        // Assigns the entityHit to the pointedEntity field in the EntityRenderer class.
        if (mc.entityRenderer != null) {
            mc.entityRenderer.pointedEntity = entityHit;
        }

        // Assigns the entityHit to the pointedEntity field in the Minecraft class.
        mc.pointedEntity = entityHit;

        // Ends the pick section.
        mc.profiler.endSection();
    }
    ```

**Comment by Foulest** [comment]
This time, I'm fairly sure I fixed it. For whatever reason, referencing the mc.objectMouseOver.entityHit variable would randomly throw the NullPointerException - probably as a result of objectMouseOver being changed after ReachFix sets it, but before ReachFix tries to access its entityHit variable - which should be the same as the RayTraceResult.

Here's the amended method, which is hopefully enough to make up for my bad pull request that didn't fix anything:

```
    public static void getMouseOver(float partialTicks) {
        Minecraft mc = Minecraft.getMinecraft();
        Entity viewEntity = mc.getRenderViewEntity();

        if (viewEntity == null) {
            return;
        }

        if (mc.player == null) {
            return;
        }

        if (mc.world == null) {
            return;
        }

        mc.profiler.startSection("pick");

        RayTraceResult result = pointedObject(viewEntity, mc.player, EnumHand.MAIN_HAND, mc.world, partialTicks);
        Entity entityHit = result.entityHit;

        mc.objectMouseOver = result;
        mc.entityRenderer.pointedEntity = entityHit;
        mc.pointedEntity = entityHit;

        mc.profiler.endSection();
    }
```

This code, specifically, fixes the problem:

```
        RayTraceResult result = pointedObject(viewEntity, mc.player, EnumHand.MAIN_HAND, mc.world, partialTicks);
        Entity entityHit = result.entityHit;

        mc.objectMouseOver = result;
        mc.entityRenderer.pointedEntity = entityHit;
        mc.pointedEntity = entityHit;
```

**Comment by Meldexun** [comment]
You can try this dev build. It implements your potential fix but it also prints an error message in chat when the issue would have happened. If you see the error message please tell me, then I can be sure that the fix is working and I can make a new release with the fix.
[ReachFix-1.12.2-1.0.11-dev1.zip](https://github.com/user-attachments/files/18332536/ReachFix-1.12.2-1.0.11-dev1.zip)

**Comment by Foulest** [comment]
![image](https://github.com/user-attachments/assets/2d1e9af9-bbe2-4fb8-ae87-6e230204b266)

**Comment by Meldexun** [comment]
~Can you also send the log?~

**Comment by Meldexun** [comment]
Nvm, issue is fixed in ReachFix 1.12.2-1.0.11
